version: "3.9"

services:

  site:
    image: web_site
    container_name: site
    build:
      context: .
      dockerfile: ./Site/Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_URLS: "http://+:12555"
      BashLearningPrivateKey: "{\"Key\":[7,5,10,32,41],\"Alphabet\":\"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!?@#$$%^\u0026*()0123456789 \"}"
      BashLearningDB: "host=localhost;Port=5432;Database=SystemDb;User Id=postgres;Password=postgres;"
      COMMAND_EXECUTOR_URL: "http://localhost:55555/ContainerDistributorApi/container"
    network_mode: host
  
  db:
    image: postgres
    environment:
      POSTGRES_DB: SystemDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    network_mode: host
    volumes:
      - /home/db
  
  db_init:
    image: bash_learning_db_init
    build:
      context: .
      dockerfile: InitialDataBase/Dockerfile
    environment:
      BashLearningDB: "host=localhost;Port=5432;Database=SystemDb;User Id=postgres;Password=postgres;"
    depends_on:
      - db
    network_mode: host

#  container-distributor:
#    image: container-distributor
#    build:
#      context: .
#      dockerfile: ./ContainerDistributor/Dockerfile
#    environment:
#      ASPNETCORE_URLS: "http://+:44444"
#    network_mode: host