version: "3.9"
  
services:

  WebApplication:
    image: web_site
    container_name: site
    build:
      context: .
      dockerfile: ./Site/Dockerfile
    depends_on: 
      - PostgresDB
    environment:
      ASPNETCORE_URLS: "http://+:12555"
      BashLearningPrivateKey: "{\"Key\":[7,5,10,32,41],\"Alphabet\":\"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!?@#$$%^\u0026*()0123456789 \"}"
      BashLearningDB: "host=localhost;Port=5432;Database=SystemDb;User Id=postgres;Password=postgres;"
    network_mode: host
    
#  server_application:
#    image: ${DOCKER_REGISTRY-}executor_image
#    container_name: executor
#    build:
#      context: .
#      dockerfile: ../BashExecutor/Dockerfile
#    restart: always
#    environment:
#      CURRENT_FOLDER: "/root"
#      COMMAND_EXECUTOR_PORT: "55555"
#    network_mode: host
#    ports:
#      - 55555
   
  PostgresDB:
    image: postgres
    environment:
      POSTGRES_DB: SystemDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    network_mode: host
    volumes:
      - /home/
        
  db_init:
    image: bash_learning_db_init
    build:
      context: .
      dockerfile: InitialDataBase/Dockerfile
    environment:
      BashLearningDB: "host=localhost;Port=5432;Database=SystemDb;User Id=postgres;Password=postgres;"
    depends_on: 
      - PostgresDB
    network_mode: host
