# This is a generated file. Not intended for manual editing.
services:
  server_application:
    build:
      context: "/home/d1qm0nd/RiderProjects/BashLearningSystem/WebApp.LearningSystem"
      dockerfile: "../BashExecutor/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net6.0/BashExecutor.dll"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "/home/d1qm0nd/.nuget/packages"
      NUGET_FALLBACK_PACKAGES: "/home/d1qm0nd/.nuget/packages"
    image: "executor_image:dev"
    ports: []
    volumes:
    - "/home/d1qm0nd/.nuget/packages:/root/.nuget/fallbackpackages"
    - "/home/d1qm0nd/RiderProjects/BashLearningSystem/BashExecutor:/app:rw"
    - "/home/d1qm0nd/RiderProjects/BashLearningSystem:/src:rw"
    working_dir: "/app"
