networks:
  solution-bridge:
    driver: bridge

services:
  WebApplication:
    image: ${DOCKER_REGISTRY-}webapp_bash_learning
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - PostgresDB
    ports: 
      - 14555:80
    
    networks: 
      - solution-bridge
  
  PostgresDB:
    image: postgres
    environment:
      POSTGRES_DB: BashLearningDB
      POSTGRES_USER: BashLearn
      POSTGRES_PASSWORD: BashLearn
    restart: no
    networks:
      - solution-bridge
    ports:
      - 5449:5432
    volumes:
      - /home/